module.exports = {
  sbpURL: 'https://portal-qa.view.com/',
  sbpBM: 'venkatesan@view.com',
  sbpBMPassword: 'viewnet195',

  sbpTA: '75rockbuild@gmail.com',
  sbpTAPassword: 'Chandran@123',

  environmentSensor: {

    'All sensors count': {

      count: 11,

    },
  },

  Building: {

    '1000 Woodbury Rd': {

      Online_Sensor: '5',
      Offline_Sensor: '5',
      Online_Sensor_OverView: '5',
      Offline_Sensor_OverView: '0',
      Active_device: '5',
      Inactive_device: '3',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '1000 Woodbury Rd, Woodbury, United States, 11797',
      Floor: '6',
      Zone: '0',
      Devices: ' 27',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '700',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["East Entrance", "North Entrance", "West Entrance", "South Entrance", "Loading Dock"],
      building_Entrance_Count : '5',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '5',
      tenantUsageCount_Last13months_Count: '5',
      tenantUsageCount_Last37months_Count: '5',
      Usage_tenantName_List_In_CalendarYear: ["Compass Group USA, Inc.", "American Business Continuity", "Petro Inc.", "HUB International Group Ne", "Utica Mutual Insurance Co"],
      Usage_tenantName_List_In_last13months: ["Compass Group USA, Inc.", "American Business Continuity", "Petro Inc.", "HUB International Group Ne", "Utica Mutual Insurance Co"],
      Usage_tenantName_List_In_last37months: ["Compass Group USA, Inc.", "American Business Continuity", "Petro Inc.", "HUB International Group Ne", "Utica Mutual Insurance Co"],
      Usage_by_Building: "Usage by Building",

    },

    '1285 Avenue of Americas': {

      Online_Sensor: '5',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '5',
      Offline_Sensor_OverView: '0',
      Active_device: '31',
      Inactive_device: '9',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '1285 Avenue of Americas, New York City, United States, 10019',
      Floor: '45',
      Zone: '0',
      Devices: ' 49',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '5321',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Bank 2 to 7", "Bank 30 to 38", "Bank 7 to 15", "Bank 14 to 24", "Bank 24 to 30"],
      building_Entrance_Count : '5',
      visitFrequencyChart: 'NA',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '4',
      tenantUsageCount_Last13months_Count: '4',
      tenantUsageCount_Last37months_Count: '4',
      Usage_tenantName_List_In_CalendarYear: ["AOA Newsstand LLC", "UBS Americas, Inc.", "Chop't 6Th Avenue LLC", "Paul Weiss Rifkind Wharton"],
      Usage_tenantName_List_In_last13months: ["AOA Newsstand LLC", "UBS Americas, Inc.", "Chop't 6Th Avenue LLC", "Paul Weiss Rifkind Wharton"],
      Usage_tenantName_List_In_last37months: ["AOA Newsstand LLC", "UBS Americas, Inc.", "Chop't 6Th Avenue LLC", "Paul Weiss Rifkind Wharton"],
      Usage_by_Building: "Usage by Building",

    },


    '230 Park Ave - The Hemsley Building': {

      Online_Sensor: '2',
      Offline_Sensor: '2',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '27',
      Inactive_device: '46',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '230 Park Ave - The Hemsley Building, New York City, United States, 10019',
      Floor: '42',
      Zone: '0',
      Devices: ' 136',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '3259',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["45th St Entrance", "46th St Entrance"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '30',
      tenantUsageCount_Last13months_Count: '30',
      tenantUsageCount_Last37months_Count: '32',
      Usage_tenantName_List_In_CalendarYear: ["Helmsley Enterprises Inc.", "Banco De La Nacion Argentina", "ORIX Real Estate Capital Holdings, LLC", "Upper Bay Opco LP", "Dome Equities, LLC", "Novartis Finance Corporation", "StoneX Group Inc.", "Desmarais LLP", "Helmsley Charitable Trust", "Thompson Family Foundation", "Relx Inc.", "Lathrop Gage LLP", "Regis USA Limited", "Tempus Labs Inc.", "Apple Tree Life Sciences Inc.", "Cheung Kong Graduate School Of Business (NA) Inc.", "JJJ&R Restaurant Inc.", "NN Investment Partners NA LLC", "Voya Financial Inc.", "Otterbourg PC", "Duane Morris LLP", "Weinberger Singer P.C.", "Onyx Renewable Partners L.P.", "Y-Mabs Therapeutics Inc.", "Neurvati Neurosciences, Inc", "Clarion Partners LLC", "Greenbacker Renewable Energy Corporation", "Robeco Institutional Asset Management Us Inc", "Lee Hecht Harrison LLC", "Maman Grand Central LLC"],
      Usage_tenantName_List_In_last13months: ["Helmsley Enterprises Inc.", "Banco De La Nacion Argentina", "ORIX Real Estate Capital Holdings, LLC", "Upper Bay Opco LP", "Dome Equities, LLC", "Novartis Finance Corporation", "StoneX Group Inc.", "Desmarais LLP", "Helmsley Charitable Trust", "Thompson Family Foundation", "Relx Inc.", "Lathrop Gage LLP", "Regis USA Limited", "Tempus Labs Inc.", "Apple Tree Life Sciences Inc.", "Cheung Kong Graduate School Of Business (NA) Inc.", "JJJ&R Restaurant Inc.", "NN Investment Partners NA LLC", "Voya Financial Inc.", "Otterbourg PC", "Duane Morris LLP", "Weinberger Singer P.C.", "Onyx Renewable Partners L.P.", "Y-Mabs Therapeutics Inc.", "Neurvati Neurosciences, Inc", "Clarion Partners LLC", "Greenbacker Renewable Energy Corporation", "Robeco Institutional Asset Management Us Inc", "Lee Hecht Harrison LLC", "Maman Grand Central LLC"],
      Usage_tenantName_List_In_last37months: ["Helmsley Enterprises Inc.", "Banco De La Nacion Argentina", "ORIX Real Estate Capital Holdings, LLC", "Upper Bay Opco LP", "Dome Equities, LLC", "Novartis Finance Corporation", "StoneX Group Inc.", "Desmarais LLP", "Helmsley Charitable Trust", "Thompson Family Foundation", "Relx Inc.", "Lathrop Gage LLP", "Regis USA Limited", "Tempus Labs Inc.", "Apple Tree Life Sciences Inc.", "Cheung Kong Graduate School Of Business (NA) Inc.", "JJJ&R Restaurant Inc.", "NN Investment Partners NA LLC", "Voya Financial Inc.", "Otterbourg PC", "Duane Morris LLP", "Weinberger Singer P.C.", "Onyx Renewable Partners L.P.", "Y-Mabs Therapeutics Inc.", "Neurvati Neurosciences, Inc", "Clarion Partners LLC", "Greenbacker Renewable Energy Corporation", "Robeco Institutional Asset Management Us Inc", "Lee Hecht Harrison LLC", "Maman Grand Central LLC", "Capital Link Inc.", "Verition Group NY Inc."],
      Usage_by_Building: "Usage by Building",

    },

    '237 Park Ave': {

      Online_Sensor: '2',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '128',
      Inactive_device: '24',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '237 Park Ave, New York City, United States, 10019',
      Floor: '25',
      Zone: '0',
      Devices: ' 159',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '3635',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["High Rise", "Low Rise"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '5',
      tenantUsageCount_Last13months_Count: '5',
      tenantUsageCount_Last37months_Count: '5',
      Usage_tenantName_List_In_CalendarYear: ["Her Majesty The Queen In", "Convene 237 Park Avenue LLC", "JP Morgan Chase N.A. MAILCODE OH1-0241", "Sticky Fingers VII LLC", "Jennison Associates LLC."],
      Usage_tenantName_List_In_last13months: ["Her Majesty The Queen In", "Convene 237 Park Avenue LLC", "JP Morgan Chase N.A. MAILCODE OH1-0241", "Sticky Fingers VII LLC", "Jennison Associates LLC."],
      Usage_tenantName_List_In_last37months: ["Her Majesty The Queen In", "Convene 237 Park Avenue LLC", "JP Morgan Chase N.A. MAILCODE OH1-0241", "Sticky Fingers VII LLC", "Jennison Associates LLC."],
      Usage_by_Building: "Usage by Building",

    },

    '32 Old Slip': {

      Online_Sensor: '4',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '4',
      Offline_Sensor_OverView: '0',
      Active_device: '52',
      Inactive_device: '5',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '32 Old Slip New York, New York, United States, 10005',
      Floor: '39',
      Zone: '0',
      Devices: ' 80',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '3196',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Bank B", "Bank A", "Bank D", "Bank C"],
      building_Entrance_Count : '4',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '15',
      tenantUsageCount_Last13months_Count: '15',
      tenantUsageCount_Last37months_Count: '15',
      Usage_tenantName_List_In_CalendarYear: ["Kuraray America Inc.", "Daiwa Capital Markets America", "Decoded Advertising LLC", "The Cementbloc Inc.", "NMS Management LP", "PolicyGenius, Inc.", "Taiwan Business Bank Co Ltd", "Brownstone Agency Inc.", "Pico Quantitative Trading Holdings LLC", "Law Office Michael Lamonsoff", "Tradition America Holdings Inc.", "Cahill Gordon & Reindel LLP", "Strategic Communications Group", "Helbiz Inc.", "FX Publications Inc"],
      Usage_tenantName_List_In_last13months: ["Kuraray America Inc.", "Daiwa Capital Markets America", "Decoded Advertising LLC", "The Cementbloc Inc.", "NMS Management LP", "PolicyGenius, Inc.", "Taiwan Business Bank Co Ltd", "Brownstone Agency Inc.", "Pico Quantitative Trading Holdings LLC", "Law Office Michael Lamonsoff", "Tradition America Holdings Inc.", "Cahill Gordon & Reindel LLP", "Strategic Communications Group", "Helbiz Inc.", "FX Publications Inc"],
      Usage_tenantName_List_In_last37months: ["Kuraray America Inc.", "Daiwa Capital Markets America", "Decoded Advertising LLC", "The Cementbloc Inc.", "NMS Management LP", "PolicyGenius, Inc.", "Taiwan Business Bank Co Ltd", "Brownstone Agency Inc.", "Pico Quantitative Trading Holdings LLC", "Law Office Michael Lamonsoff", "Tradition America Holdings Inc.", "Cahill Gordon & Reindel LLP", "Strategic Communications Group", "Helbiz Inc.", "FX Publications Inc"],
      Usage_by_Building: "Usage by Building",

    },

    '333 Earle Ovington Blvd - The Omni': {

      Online_Sensor: '3',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '3',
      Offline_Sensor_OverView: '0',
      Active_device: '14',
      Inactive_device: '0',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '333 Earle Ovington Blvd - The Omni, Uniondale, United States, 11553',
      Floor: '12',
      Zone: '0',
      Devices: ' 28',
      SoundStatus: 'NA',
      ThermalStatus: 'NA',
      AirStatus: 'NA',
      LightStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1387',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Lobby West Entrance", "Lobby South Entrance", "Lower Level Entrance"],
      building_Entrance_Count : '3',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '10',
      tenantUsageCount_Last13months_Count: '10',
      tenantUsageCount_Last37months_Count: '10',
      Usage_tenantName_List_In_CalendarYear: ["Congdon Flaherty O'Callaghan", "Long Island Power Authority", "Garden Gourmet at OMNI, Inc.", "Arbor Multifamily Lending LLC", "Optimuss Fitness Corp.", "Forchelli Deegan Terrana LLP", "Penn Mutual Life Insurance Co", "Concordia International Forwarding Corp.", "Federal Insurance Company", "Sahn Ward Coschignano PLLC"],
      Usage_tenantName_List_In_last13months: ["Congdon Flaherty O'Callaghan", "Long Island Power Authority", "Garden Gourmet at OMNI, Inc.", "Arbor Multifamily Lending LLC", "Optimuss Fitness Corp.", "Forchelli Deegan Terrana LLP", "Penn Mutual Life Insurance Co", "Concordia International Forwarding Corp.", "Federal Insurance Company", "Sahn Ward Coschignano PLLC"],
      Usage_tenantName_List_In_last37months: ["Congdon Flaherty O'Callaghan", "Long Island Power Authority", "Garden Gourmet at OMNI, Inc.", "Arbor Multifamily Lending LLC", "Optimuss Fitness Corp.", "Forchelli Deegan Terrana LLP", "Penn Mutual Life Insurance Co", "Concordia International Forwarding Corp.", "Federal Insurance Company", "Sahn Ward Coschignano PLLC"],
      Usage_by_Building: "Usage by Building",

    },

    '340 Madison Ave': {

      Online_Sensor: '2',
      Offline_Sensor: '2',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '48',
      Inactive_device: '21',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '340 Madison Ave, New York City, United States, 10036',
      Floor: '24',
      Zone: '0',
      Devices: ' 99',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1258',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["Upper House", "Lower House"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '12',
      tenantUsageCount_Last13months_Count: '12',
      tenantUsageCount_Last37months_Count: '14',
      Usage_tenantName_List_In_CalendarYear: ["Allen Edmonds Shoe Corp.", "Wright 344 Madison Ave. Inc.", "Old Orchard Capital Management LP", "Linda M. Sarett DDS.", "United States Of America OCC", "Barings LLC", "Cellco Partnership (Flg1-300)", "Fifth Church Of Christ", "Fis Systems International Inc", "CFGI LLC", "The Bansk Group LLC", "Altus Group Us Inc."],
      Usage_tenantName_List_In_last13months: ["Allen Edmonds Shoe Corp.", "Wright 344 Madison Ave. Inc.", "Old Orchard Capital Management LP", "Linda M. Sarett DDS.", "United States Of America OCC", "Barings LLC", "Cellco Partnership (Flg1-300)", "Fifth Church Of Christ", "Fis Systems International Inc", "CFGI LLC", "The Bansk Group LLC", "Altus Group Us Inc."],
      Usage_tenantName_List_In_last37months: ["Allen Edmonds Shoe Corp.", "Wright 344 Madison Ave. Inc.", "Old Orchard Capital Management LP", "Linda M. Sarett DDS.", "United States Of America OCC", "Barings LLC", "Cellco Partnership (Flg1-300)", "Fifth Church Of Christ", "Fis Systems International Inc", "CFGI LLC", "The Bansk Group LLC", "Altus Group Us Inc.", "Corra Technology Inc.", "Trinity Place Holdings Inc"],
      Usage_by_Building: "Usage by Building",

    },

    '37-18 Northern Blvd - Standard Motors': {   

      Online_Sensor: '0',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '0',
      Offline_Sensor_OverView: '0',
      Active_device: '6',
      Inactive_device: '0',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '37-18 Northern Blvd - Standard Motors, Long Island City, United States, 11101',
      Floor: '8',
      Zone: '0',
      Devices: ' 38',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '454',
      building_OccupancyChart: 'NA',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance1 : 'NA',
      build_Entrance2 : 'NA',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Real_Time_Occ_percentage   : 'NA',
      Avg_Occ_overlast90days     : 'NA',
      Peak_Occ_overlast90days    : 'NA',
      Total_People_Count         : 'NA',
      RealTimefoot_traffic       : 'NA',
      Avgfoottraffic_90days      : 'NA',
      Building_Entrance          : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : 'NA',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '25',
      tenantUsageCount_Last13months_Count: '25',
      tenantUsageCount_Last37months_Count: '26',
      Usage_tenantName_List_In_CalendarYear: ["Nana Wall Systems Inc.", "Caples Jefferson Architects", "Jim Henson Company", "Ideas By Barbara", "Mechanical Energy Solutions, Inc.", "The I Grace Company", "Aime Leon Dore, Inc.", "DLG Adv LLC", "Laurent-Perrier Us Inc", "Broadview Networks Inc", "Eastman Kodak Company", "Kanan Productions, Inc.", "Chinese Theatre Works Inc", "Eloquii Design Inc.", "Almondnet Inc", "Shalat Architects PC", "Creative Woodcraft", "Eversys, Inc.", "RIMOWA Distribution, Inc.", "R. Cano Group Inc", "Standard Motors Products Inc", "Spy Tec International, Inc.", "Narofsky Architecture", "Klim Inc", "Vandeb Editions Inc"],
      Usage_tenantName_List_In_last13months: ["Nana Wall Systems Inc.", "Caples Jefferson Architects", "Jim Henson Company", "Ideas By Barbara", "Mechanical Energy Solutions, Inc.", "The I Grace Company", "Aime Leon Dore, Inc.", "DLG Adv LLC", "Laurent-Perrier Us Inc", "Broadview Networks Inc", "Eastman Kodak Company", "Kanan Productions, Inc.", "Chinese Theatre Works Inc", "Eloquii Design Inc.", "Almondnet Inc", "Shalat Architects PC", "Creative Woodcraft", "Eversys, Inc.", "RIMOWA Distribution, Inc.", "R. Cano Group Inc", "Standard Motors Products Inc", "Spy Tec International, Inc.", "Narofsky Architecture", "Klim Inc", "Vandeb Editions Inc"],
      Usage_tenantName_List_In_last37months: ["Nana Wall Systems Inc.", "Caples Jefferson Architects", "Jim Henson Company", "Ideas By Barbara", "Mechanical Energy Solutions, Inc.", "The I Grace Company", "Aime Leon Dore, Inc.", "DLG Adv LLC", "Laurent-Perrier Us Inc", "Broadview Networks Inc", "Eastman Kodak Company", "Kanan Productions, Inc.", "Chinese Theatre Works Inc", "Eloquii Design Inc.", "Almondnet Inc", "Shalat Architects PC", "Creative Woodcraft", "Eversys, Inc.", "RIMOWA Distribution, Inc.", "R. Cano Group Inc", "Standard Motors Products Inc", "Spy Tec International, Inc.", "Narofsky Architecture", "Klim Inc", "Vandeb Editions Inc", "B.Thayer Associates"],
      Usage_by_Building: "Usage by Building",
      peak_Occ_percent : 'NA',
      real_Time_Occ_percent: 'NA',

    },

    '450 Lexington Ave': {

      Online_Sensor: '5',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '5',
      Offline_Sensor_OverView: '0',
      Active_device: '79',
      Inactive_device: '25',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '450 Lexington Ave, New York City, United States, 10036',
      Floor: '37',
      Zone: '0',
      Devices: ' 121',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '2705',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["31st to 40th", "Conf Rm 8th Flr", "Loading Dock", "19th to 30th", "10th to 19th"],
      building_Entrance_Count : '5',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '11',
      tenantUsageCount_Last13months_Count: '11',
      tenantUsageCount_Last37months_Count: '11',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Athene USA Corporation", "AIP LLC", "Marathon Capital LLC", "Chaincode Labs Inc.", "Stepstone Group LP", "Spear Street Capital", "Everest Medicines Ltd.", "Fedex Kinkos - Store#4464", "Nagashima Ohno & Tsunematsu NY LLP", "Warburg Pincus LLC", "Davis Polk & Wardwell"],
      Usage_tenantName_List_In_last13months: ["Athene USA Corporation", "AIP LLC", "Marathon Capital LLC", "Chaincode Labs Inc.", "Stepstone Group LP", "Spear Street Capital", "Everest Medicines Ltd.", "Fedex Kinkos - Store#4464", "Nagashima Ohno & Tsunematsu NY LLP", "Warburg Pincus LLC", "Davis Polk & Wardwell"],
      Usage_tenantName_List_In_last37months: ["Athene USA Corporation", "AIP LLC", "Marathon Capital LLC", "Chaincode Labs Inc.", "Stepstone Group LP", "Spear Street Capital", "Everest Medicines Ltd.", "Fedex Kinkos - Store#4464", "Nagashima Ohno & Tsunematsu NY LLP", "Warburg Pincus LLC", "Davis Polk & Wardwell"],
      Environment_Status: 'NA',
    },

    '470 Vanderbilt Ave': {

      Online_Sensor: 'NA',
      Offline_Sensor: 'NA',
      Active_device: '0',
      Inactive_device: '39',
      Building_Manager: '39',
      Tenant_Admin: '94',
      Address: '470 Vanderbilt Ave, New York City, United States, 10036',
      Floor: '10',
      Zone: '0',
      Devices: ' 45',
      Last_updated_time: 'NA',
      Environment_Status: 'NA',
      Occupancy_Page: 'NA',
      SoundStatus: 'NA',
      ThermalStatus: 'NA',
      AirStatus: 'NA',
      LightStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'NA',
      total_People: '1187',
      Build_Occ_last_Update_Time: 'NA',
      real_Time_Occ_percent: 'NA',
      peak_Occ_percent: 'NA',
      days_PeakUnique_User: 'NA',
      realandPeak_count: 'NA',
      total_Real_Peak: 'NA',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      environment_SeeMore: 'Local Weather Forecast',
      building_Occupancy_Seemore: 'NA',
       occ_last_Update_Time       : 'NA',
       Building_Occupancy_Title   : 'NA',
       Real_Time_Occ_percentage   : 'NA',
       Avg_Occ_overlast90days     : 'NA',
       Peak_Occ_overlast90days    : 'NA',
       Total_People_Count         : 'NA',
       Lobby_FootTraffic_Tiltle   : 'NA',
       LobbyTraffic_LastupadteTime: 'NA',
       RealTimefoot_traffic       : 'NA',
       Avgfoottraffic_90days      : 'NA',
       Occupancy_DetailsTitle     : 'NA',
       Occ_Details_LastupadteTime : 'NA',
       Building_Entrance          : 'NA',
       Occupancy_UsagePage : 'NA',
       Occupancy_Page : 'NA',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '5',
      tenantUsageCount_Last13months_Count: '5',
      tenantUsageCount_Last37months_Count: '5',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["The League School", "Switchnet Corp", "NYC Housing Authority", "Arbor E&T LLC D/B/A Rescare Workforce Services", "Mhany Management Inc."],
      Usage_tenantName_List_In_last13months: ["The League School", "Switchnet Corp", "NYC Housing Authority", "Arbor E&T LLC D/B/A Rescare Workforce Services", "Mhany Management Inc."],
      Usage_tenantName_List_In_last37months: ["The League School", "Switchnet Corp", "NYC Housing Authority", "Arbor E&T LLC D/B/A Rescare Workforce Services", "Mhany Management Inc."],

    },


    '48 South Service Rd': {

      Online_Sensor: '6',
      Offline_Sensor: '4',
      Online_Sensor_OverView: '6',
      Offline_Sensor_OverView: '4',
      Active_device: '5',
      Inactive_device: '5',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '48 South Service Rd, New York City, United States, 10036',
      Floor: '6',
      Zone: '0',
      Devices: ' 29',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '304',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["South Entrance", "North Entrance", "Cafe", "West Entrance"],
      building_Entrance_Count : '4',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '3',
      tenantUsageCount_Last13months_Count: '3',
      tenantUsageCount_Last37months_Count: '4',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Principal Life Insurance Co", "Citizens Bank N.A.", "Evero Corporation"],
      Usage_tenantName_List_In_last13months: ["Principal Life Insurance Co", "Citizens Bank N.A.", "Evero Corporation"],
      Usage_tenantName_List_In_last37months: ["Principal Life Insurance Co", "Citizens Bank N.A.", "Evero Corporation", "Advisors Asset Management Inc"],
      lowestMonthEUI: '0',

    },

    '5 Times Square': {

      Online_Sensor: 'NA',
      Offline_Sensor: 'NA',
      Active_device: '66',
      Inactive_device: '15',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: 'Five Times Square, New York, New York City, United States, 10036',
      Floor: '43',
      Zone: '0',
      Devices: ' 83',
      SoundStatus: 'NA',
      Last_updated_time: 'NA',
      Occupancy_Page: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'NA',
      total_People: '514',
      Build_Occ_last_Update_Time: 'NA',
      real_Time_Occ_percent: 'NA',
      peak_Occ_percent: 'NA',
      days_PeakUnique_User: 'NA',
      realandPeak_count: 'NA',
      total_Real_Peak: 'NA',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      environment_SeeMore: 'Local Weather Forecast',
      building_Occupancy_Seemore: 'NA',
      occ_last_Update_Time       : 'NA',
      Building_Occupancy_Title   : 'NA',
      Real_Time_Occ_percentage   : 'NA',
      Avg_Occ_overlast90days     : 'NA',
      Peak_Occ_overlast90days    : 'NA',
      Total_People_Count         : 'NA',
      Lobby_FootTraffic_Tiltle   : 'NA',
      LobbyTraffic_LastupadteTime: 'NA',
      RealTimefoot_traffic       : 'NA',
      Avgfoottraffic_90days      : 'NA',
      Occupancy_DetailsTitle     : 'NA',
      Occ_Details_LastupadteTime : 'NA',
      Building_Entrance          : 'NA',
      Occupancy_UsagePage : 'NA',
      Occupancy_Page : 'NA',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      energyPage: 'NA',
      tenantUsageCount_CalendarYear_Count: '0',
      tenantUsageCount_Last13months_Count: '0',
      tenantUsageCount_Last37months_Count: '1',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: 'NA',
      Usage_tenantName_List_In_last13months: 'NA',
      
    },

    '50 Charles Lindbergh Blvd': {

      Online_Sensor: '2',
      Offline_Sensor: '2',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '4',
      Inactive_device: '8',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: 'Uniondale, NY, New York City, United States, 11553',
      Floor: '8',
      Zone: '0',
      Devices: ' 21',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '563',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["West Entrance", "East Entrance"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '4',
      tenantUsageCount_Last13months_Count: '4',
      tenantUsageCount_Last37months_Count: '5',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["First Nationwide Title Agency", "Medical Recovery Collections Group Inc.", "Rockit Solutions, LLC", "Liberty Mutual Insurance Co."],
      Usage_tenantName_List_In_last13months: ["First Nationwide Title Agency", "Medical Recovery Collections Group Inc.", "Rockit Solutions, LLC", "Liberty Mutual Insurance Co."],
      Usage_tenantName_List_In_last37months: ["First Nationwide Title Agency", "Medical Recovery Collections Group Inc.", "Rockit Solutions, LLC", "Liberty Mutual Insurance Co.", "Volt Information Sciences Inc"],

    },

    '530 5th Ave': {

      Online_Sensor: '2',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '13',
      Inactive_device: '27',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '530 5th Ave, New York City, United States, 10036',
      Floor: '29',
      Zone: '0',
      Devices: ' 48',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1500',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Floor 1 to 10", "Floor 11 to 26"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      energyPage: 'NA',
      tenantUsageCount_CalendarYear_Count: '0',
      tenantUsageCount_Last13months_Count: '0',
      tenantUsageCount_Last37months_Count: '2',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: 'NA',
      Usage_tenantName_List_In_last13months: 'NA',

    },

    '58 South Service Rd': {

      Online_Sensor: '6',
      Offline_Sensor: '6',
      Online_Sensor_OverView: '6',
      Offline_Sensor_OverView: '0',
      Active_device: '5',
      Inactive_device: '3',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '58 South Service Rd, Melville, United States, 11747',
      Floor: '6',
      Zone: '0',
      Devices: ' 37',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '736',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["South Entrance", "Cafe Stairs", "Garage Entrance", "East Entrance", "North Entrance", "West Entrance"],
      building_Entrance_Count : '6',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '12',
      tenantUsageCount_Last13months_Count: '12',
      tenantUsageCount_Last37months_Count: '13',
      Usage_by_Building: "Usage by Building", 
      Usage_tenantName_List_In_CalendarYear: ["American Advisors Group", "Wells Fargo Bank N.A. (BE#144273)", "Andersen Tax LLC", "Ladenburg Thalmann & Co.Inc", "Morgan Stanley Smith Barney", "Signature Bank", "Zurich American Insurance Co.", "Avalonbay Communities Inc.", "Dale Carnegie & Associates Inc.", "CBRE Inc.", "RGRD New York Leasing Corp", "Jackson Lewis P.C."],
      Usage_tenantName_List_In_last13months: ["American Advisors Group", "Wells Fargo Bank N.A. (BE#144273)", "Andersen Tax LLC", "Ladenburg Thalmann & Co.Inc", "Morgan Stanley Smith Barney", "Signature Bank", "Zurich American Insurance Co.", "Avalonbay Communities Inc.", "Dale Carnegie & Associates Inc.", "CBRE Inc.", "RGRD New York Leasing Corp", "Jackson Lewis P.C."],
      Usage_tenantName_List_In_last37months: ["American Advisors Group", "Wells Fargo Bank N.A. (BE#144273)", "Andersen Tax LLC", "Ladenburg Thalmann & Co.Inc", "Morgan Stanley Smith Barney", "Signature Bank", "Zurich American Insurance Co.", "Avalonbay Communities Inc.", "Dale Carnegie & Associates Inc.", "CBRE Inc.", "RGRD New York Leasing Corp", "Jackson Lewis P.C.", "Avison Young - New York LLC"],
      Environment_Status: 'NA',

    },

    '601 W 26th St - Starrett-Lehigh Building': {

      Online_Sensor: '0',
      Offline_Sensor: '13',
      Online_Sensor_OverView: '0',
      Offline_Sensor_OverView: '11',
      Active_device: '6',
      Inactive_device: '5',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '601 W 26th St - Starret-Lehigh Building, New York City, United States, 10001',
      Floor: '24',
      Zone: '0',
      Devices: ' 82',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '2875',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance1 : 'NA',
      build_Entrance2 : 'NA',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : 'NA',
      Avg_Occ_overlast90days_Data : '0',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '10',
      tenantUsageCount_Last13months_Count: '10',
      tenantUsageCount_Last37months_Count: '10',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["811 Media LLC", "Canada Goose Us Inc", "Boston Concessions Group of NY, Ltd.", "Cinema Vision, Inc.", "Amy Lau Design Inc.", "Burn & Broad", "601 W Companies", "Broadview Networks Inc.", "Crown Castle Fiber LLC", "Canoe Studios"],
      Usage_tenantName_List_In_last13months: ["811 Media LLC", "Canada Goose Us Inc", "Boston Concessions Group of NY, Ltd.", "Cinema Vision, Inc.", "Amy Lau Design Inc.", "Burn & Broad", "601 W Companies", "Broadview Networks Inc.", "Crown Castle Fiber LLC", "Canoe Studios"],
      Usage_tenantName_List_In_last37months: ["811 Media LLC", "Canada Goose Us Inc", "Boston Concessions Group of NY, Ltd.", "Cinema Vision, Inc.", "Amy Lau Design Inc.", "Burn & Broad", "601 W Companies", "Broadview Networks Inc.", "Crown Castle Fiber LLC", "Canoe Studios"],
      peak_Occ_percent : 'NA',
      real_Time_Occ_percent: 'NA',

    },

    '61 Broadway': {

      Online_Sensor: '3',
      Offline_Sensor: '1',
      Online_Sensor_OverView: '3',
      Offline_Sensor_OverView: '0',
      Active_device: '44',
      Inactive_device: '6',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '61 Broadway, New York City, United States, 10006',
      Floor: '36',
      Zone: '0',
      Devices: ' 91',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1395',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["Broadway Entrance", "Trinity Entrance"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '18',
      tenantUsageCount_Last13months_Count: '19',
      tenantUsageCount_Last37months_Count: '21',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Corp For Supportive Housing", "Chicago Options Exchange Corp", "Luminary Labs LLC", "Guardian News & Media LLC", "Collibra Inc", "City And State New York LLC", "Legends Hospitality LLC", "Eliassen Group, LLC", "Giordano, Glaws & Fenstermacher, LLP", "The City of New York", "DP Group Inc", "Hudson Meridian Construction Group LLC", "Broadway Chiropractic Assc PC", "Vincenti & Vincenti, P.C.", "Hoffman Mulligan CPA's LLC", "JMT of New York, Inc.", "Alfred Club Inc.", "Ubiqus Reporting Inc"],
      Usage_tenantName_List_In_last13months: ["Corp For Supportive Housing", "Chicago Options Exchange Corp", "Luminary Labs LLC", "Guardian News & Media LLC", "Collibra Inc", "City And State New York LLC", "Legends Hospitality LLC", "Eliassen Group, LLC", "Giordano, Glaws & Fenstermacher, LLP", "The City of New York", "DP Group Inc", "Hudson Meridian Construction Group LLC", "Broadway Chiropractic Assc PC", "Vincenti & Vincenti, P.C.", "Hoffman Mulligan CPA's LLC", "JMT of New York, Inc.", "Alfred Club Inc.", "Ubiqus Reporting Inc", "Interlude US, Inc."],
      Usage_tenantName_List_In_last37months: ["Corp For Supportive Housing", "Chicago Options Exchange Corp", "Luminary Labs LLC", "Guardian News & Media LLC", "Collibra Inc", "City And State New York LLC", "Legends Hospitality LLC", "Eliassen Group, LLC", "Giordano, Glaws & Fenstermacher, LLP", "The City of New York", "DP Group Inc", "Hudson Meridian Construction Group LLC", "Broadway Chiropractic Assc PC", "Vincenti & Vincenti, P.C.", "Hoffman Mulligan CPA's LLC", "JMT of New York, Inc.", "Alfred Club Inc.", "Ubiqus Reporting Inc", "Furman Kornfeld & Brennan LLP", "Professional Staff Congress", "Interlude US, Inc."],

    },

    '620 Avenue of Americas': {

      Online_Sensor: '1',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '1',
      Offline_Sensor_OverView: '0',
      Active_device: '4',
      Inactive_device: '10',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '620 Avenue of Americas, New York City, United States, 10036',
      Floor: '12',
      Zone: '0',
      Devices: ' 15',
      SoundStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1425',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance2 : 'NA',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Main Entrance Occupancy"],
      building_Entrance_Count : '1',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      energyPage: 'NA',
      Usage_by_Building: "Usage by Building", 

    },

    '625 Rxr Plz - RXR Plaza': {

      Online_Sensor: '7',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '7',
      Offline_Sensor_OverView: '0',
      Active_device: '33',
      Inactive_device: '6',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '625 Rxr Plz - RXR Plaza, Uniondale, United States, 11556',
      Floor: '27',
      Zone: '0',
      Devices: ' 80',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '2527',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["Farrell Fritz", "Lobby East South Elevator", "Lobby West", "Plaza West", "Plaza East", "Glass Link", "Lobby East North Elevator Bank"],
      building_Entrance_Count : '7',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '11',
      tenantUsageCount_Last13months_Count: '11',
      tenantUsageCount_Last37months_Count: '11',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Allstate Insurance Company", "Westerman Ball Ederer Miller", "Flushing Bank", "Rivkin Radler LLC", "Openlink Financial LLC", "RexCorp Property Management", "Air Charter Service Inc.", "Harbor Day Care Center Inc.", "BNY Mellon Securities Corporation", "Humana Marketpoint Inc.", "Ruskin Moscou Faltischek P.C."],
      Usage_tenantName_List_In_last13months: ["Allstate Insurance Company", "Westerman Ball Ederer Miller", "Flushing Bank", "Rivkin Radler LLC", "Openlink Financial LLC", "RexCorp Property Management", "Air Charter Service Inc.", "Harbor Day Care Center Inc.", "BNY Mellon Securities Corporation", "Humana Marketpoint Inc.", "Ruskin Moscou Faltischek P.C.", "Urban Solutions LLC"],
      Usage_tenantName_List_In_last37months: ["Allstate Insurance Company", "Westerman Ball Ederer Miller", "Flushing Bank", "Rivkin Radler LLC", "Openlink Financial LLC", "RexCorp Property Management", "Air Charter Service Inc.", "Harbor Day Care Center Inc.", "BNY Mellon Securities Corporation", "Humana Marketpoint Inc.", "Ruskin Moscou Faltischek P.C."],

    },

    '68 South Service Rd': {

      Online_Sensor: '0',
      Offline_Sensor: '12',
      Online_Sensor_OverView: '0',
      Offline_Sensor_OverView: '6',
      Active_device: '4',
      Inactive_device: '6',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '68 South Service Rd, Melville, United States, 11747',
      Floor: '6',
      Zone: '0',
      Devices: ' 28',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '818',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["East Entrance", "North Entrance", "South Entrance", "West Entrance", "Cafe Stairs", "Garage Entrance"],
      building_Entrance_Count : '6',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '3',
      tenantUsageCount_Last13months_Count: '3',
      tenantUsageCount_Last37months_Count: '3',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear:  ["World Wide Specialty Programs", "Global Securitization Service", "Comtech Telecommunications"],
      Usage_tenantName_List_In_last13months:  ["World Wide Specialty Programs", "Global Securitization Service", "Comtech Telecommunications"],
      Usage_tenantName_List_In_last37months:  ["World Wide Specialty Programs", "Global Securitization Service", "Comtech Telecommunications"],

    },

    '75 Rockefeller Plaza': {

      Online_Sensor: '3',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '3',
      Offline_Sensor_OverView: '0',
      Active_device: '40',
      Inactive_device: '16',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '75 Rockefeller Plaza, New York City, United States, 10019',
      Floor: '39',
      Zone: '0',
      Devices: ' 136',
      SoundStatus: 'NA',
      page_Title1: 'Visit Frequency',
      unique_Users: 'Total Unique Users',
      totalSwips: 'Total SWIPES',
      swips_Buildandspace: 'Total swipes into building and tenant spaces',
      installvisitfrquencyText: 'Installed Visit Frequency Devices',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1488',
      occupancy_Usage_SeeMore: 'Total Building Visit Frequency',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      buildAccess_Text: 'Building Access',
      access_Summary_Text : 'Access Summary',
      total_BuildingVisitFrequency_Text : 'Total Building Visit Frequency',
      tenant_Usage_IntensityText : 'Tenant Usage Intensity',
      Building_Entrance_Name_list : ["Low Rise East", "High Rise", "Low Rise West"],
      building_Entrance_Count : '3',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      lowestMonthEUI: '0',
      tenantUsageCount_CalendarYear_Count: '16',
      tenantUsageCount_Last13months_Count: '17',
      tenantUsageCount_Last37months_Count: '19',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Urban Solutions LLC", "McGill Global Risk Solutions LLC", "SK Telecom TMT Investment Corp", "Merrill Lynch Pierce Fenner", "Aysen Corp.", "HighPost Capital LLC", "Essex Woodlands Management, Inc.", "American Girl Retail Inc.", "Dore Partnership LLC", "Adverity Inc.", "Southern Land Company LLC", "75 Rock Plz Tenant LLC Wework", "Coqual Inc", "Erste Group Bank Ag New York Branch", "Crestline Research Sub, L.P.", "RMB Securities USA Inc.", "RexCorp Property Management"],
      Usage_tenantName_List_In_last13months: ["Urban Solutions LLC", "McGill Global Risk Solutions LLC", "SK Telecom TMT Investment Corp", "Merrill Lynch Pierce Fenner", "Aysen Corp.", "HighPost Capital LLC", "Essex Woodlands Management, Inc.", "American Girl Retail Inc.", "Dore Partnership LLC", "Adverity Inc.", "Southern Land Company LLC", "75 Rock Plz Tenant LLC Wework", "Coqual Inc", "Erste Group Bank Ag New York Branch", "Crestline Research Sub, L.P.", "RMB Securities USA Inc.", "RexCorp Property Management", "Tarsadia Capital, LLC"],
      Usage_tenantName_List_In_last37months: ["Urban Solutions LLC", "McGill Global Risk Solutions LLC", "SK Telecom TMT Investment Corp", "Merrill Lynch Pierce Fenner", "Aysen Corp.", "HighPost Capital LLC", "Essex Woodlands Management, Inc.", "American Girl Retail Inc.", "Dore Partnership LLC", "Adverity Inc.", "Southern Land Company LLC", "75 Rock Plz Tenant LLC Wework", "Coqual Inc", "Erste Group Bank Ag New York Branch", "Crestline Research Sub, L.P.", "RMB Securities USA Inc.", "RexCorp Property Management", "Tarsadia Capital, LLC", "FE International, Inc.", "BasePoint Group Inc."],

    },

    '825 8th Ave - Worldwide Plaza': {

      Online_Sensor: '2',
      Offline_Sensor: '0',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: '35',
      Inactive_device: '60',
      Building_Manager: '150',
      Tenant_Admin: '94',
      Address: '825 8th Ave - Worldwide Plaza, New York City, United States, 10019',
      Floor: '51',
      Zone: '0',
      Devices: ' 74',
      SoundStatus: 'NA',
      LightStatus: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '1373',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      buildOccTextSeeMore: 'Building Occupancy  ',
      environment_SeeMore: 'Local Weather Forecast',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["Floor 18 to 38", "Floor 11 to 14"],
      building_Entrance_Count : '2',
      energypage_Title: 'Energy Usage',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      tenantUsageCount_CalendarYear_Count: '9',
      tenantUsageCount_Last13months_Count: '9',
      tenantUsageCount_Last37months_Count: '10',
      Environment_Status: 'NA',
      Usage_by_Building: "Usage by Building",
      Usage_tenantName_List_In_CalendarYear: ["Rubenstein Associates Inc. And Rubenstein Communications Inc.", "Just Salad WWP LLC", "M. Shanken Communications Inc", "CBS Broadcasting Inc.", "Pret 825 Eight Avenue Inc.", "Wnet.Org And Thirteen", "West Monroe Partners, Inc. and West Monroe Partners, LLC", "Nomura Holding America Inc.", "Wilk Auslander, LLP"],
      Usage_tenantName_List_In_last13months: ["Rubenstein Associates Inc. And Rubenstein Communications Inc.", "Just Salad WWP LLC", "M. Shanken Communications Inc", "CBS Broadcasting Inc.", "Pret 825 Eight Avenue Inc.", "Wnet.Org And Thirteen", "West Monroe Partners, Inc. and West Monroe Partners, LLC", "Nomura Holding America Inc.", "Wilk Auslander, LLP"],
      Usage_tenantName_List_In_last37months: ["Rubenstein Associates Inc. And Rubenstein Communications Inc.", "Just Salad WWP LLC", "M. Shanken Communications Inc", "CBS Broadcasting Inc.", "Pret 825 Eight Avenue Inc.", "Wnet.Org And Thirteen", "West Monroe Partners, Inc. and West Monroe Partners, LLC", "Nomura Holding America Inc.", "Wilk Auslander, LLP", "WebMD LLC"],
    },

    'View Chennai': {

      Online_Sensor: '2',
      Offline_Sensor: '1',
      Online_Sensor_OverView: '2',
      Offline_Sensor_OverView: '0',
      Active_device: 'NA',
      Inactive_device: 'NA',
      Address: 'Chennai, Milpitas, USA, 95035',
      ThermalStatus: 'NA',
      AirStatus: 'NA',
      LightStatus: 'NA',
      Environment_Status: 'NA',
      SoundStatus: 'NA',
      Occ_Offline_Sensor: '1',
      last_Update_Time: 'NA',
      page_Title1: 'NA',
      unique_Users: 'NA',
      totalSwips: 'NA',
      swips_Buildandspace: 'NA',
      installvisitfrquencyText: 'NA',
      Unique_Users_Count: 'NA',
      Total_Swips_Count: 'NA',
      Visit_Frequency_Devices_Count: 'NA',
      building_Occ_Title: 'Building Occupancy',
      total_People: '40',
      visit_Frequency_Seemore: 'NA',
      visitFrequencyChart: 'NA',
      environment_Seemorecl: 'NA',
      buildOccTextSeeMore: 'Building Occupancy  ',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      buildOcc_Details_Title : 'Building Occupancy Details',
      build_Entrance3 : 'NA',
      build_Entrance4 : 'NA',
      build_Entrance5 : 'NA',
      build_Entrance6 : 'NA',
      build_Entrance7 : 'NA',
      RealTimefoot_traffic       : 'NA',
      Avgfoottraffic_90days      : 'NA',
      Occupancy_UsagePage : 'NA',
      Building_Entrance_Name_list : ["View_Gate_1", "View_Gate_2"],
      building_Entrance_Count : '2',
      energyPage: 'NA',
      Usage_by_Building: "Usage by Building",
    },
  },
  Building_OverView_page: {

    'Over View Page Occupancy List': {

      Building1: '386',
      Building2: '700',
      Building3: '5321',
      Building4: '1117',
      Building5: '50',
      Building6: '3259',
      Building7: '3635',
      Building8: '3196',
      Building9: '1387',
      Building10: '1258',
      Building11: 'NA',
      Building12: '2705',
      Building13: 'NA',
      Building14: '304',
      Building15: '514',
      Building16: '563',
      Building17: '1500',
      Building18: '736',
      Building19: '2875',
      Building20: '1395',
      Building21: '862',
      Building22: '2527',
      Building23: '818',
      Building24: '1488',
      Building25: '4889',

    }
  },


  Building1: {

    'Adverity Inc': {
      Address: '75 Rockefeller Plaza, New York City, United States, 10019',
      building_name: '75 Rockefeller Plaza',
      page_Title1: 'Visit Frequency',
      unique_Users_Title: 'Total Unique Users',
      page_Title2: 'Energy',
      environment_SeeMore: 'Local Weather Forecast',
      occupancy_Usage_SeeMore: 'Visit Frequency',
      energy_SeeMore: 'Energy Usage',
      monthUsageText: 'Average Monthly Usage',
      month_EUI_Text: 'Average Monthly EUI',
      HigheneryUsageName: 'Adverity Inc.',
      LowenergyUsageName: 'Adverity Inc.',
      averageUsage_Txt: 'Average monthly tenant usage',
      energy_Intensity_Txt: 'Energy Use Intensity',
      total_People: '1488',
      lobbyTitle: 'Lobby Foot Traffic',
      buildOccupancy_Txt: 'Building Occupancy',
      visitFrequencyTxt: 'Visit Frequency',
      Aggregate_user_swipes: 'Aggregate user swipes into your spaces',
      Peak_Unique_daily_users: 'Peak unique daily users',
      occ_OnlineCount: '3',
      occ_OfflineCount: '0',
      buildOccTextSeeMore: 'Building Occupancy  ',
      entrance1: 'High Rise',
      entrance2: 'Low Rise West',
      entrance3: 'Low Rise East',
      userID: '75rocknewuser1@gmail.com'
    },
    'Southern Land Company LLC': {
      Address: '75 Rockefeller Plaza, New York City, United States, 10019',
      // SoundStatus:'NA',
      building_name: '75 Rockefeller Plaza',
      page_Title1: 'Visit Frequency',
      unique_Users_Title: 'Total Unique Users Today',
      page_Title2: 'Energy',
      environment_SeeMore: 'Local Weather Forecast',
      occupancy_Usage_SeeMore: 'Visit Frequency',
      energy_SeeMore: 'Energy Usage',
      monthUsageText: 'Average Monthly Usage',
      month_EUI_Text: 'Average Monthly EUI',
    }
  },

  newUser: {

    'userData': {
      emailId: '75rocknewuser1@gmail.com',
      Name: '75Rock Building',
      userNo: '1234567890',
      persona: 'Tenant Admin',

    }
  },

  overViewPage: {

    'overView': {

      buildingCount: '21',
      chatHoverTitle: 'portfolio occupancy',
      total_occupancyCount: 38660,
      last7DaysCount: 7,
      last14DaysCount: 14,
      last30daysCount: 30,
      yesterdayCount: 24,
    },
  },
}
